module.exports = {

//$$('a').map(a=> a.text)



//"Act of Independence of Lithuania", //č
//"Burning of Parliament", //Think about abbreaviations
//"Farthest South", //sentence 26 seperate 2 sentences
//"Free State of Galveston", // remove last sentence
  articles : ["1689 Boston revolt",
  "1740 Batavia massacre",
  "1907 Tiflis bank robbery",
  "1964 Brinks Hotel bombing",
  "1981 Irish hunger strike",
  "Act of Independence of Lithuania",
  "Amundsen's South Pole expedition",
  "Ancient Egypt",
  "Assassination of William McKinley",
  "Bal des Ardents",
  "Benedict Arnold's expedition to Quebec",
  "Birmingham campaign",
  "Blackwater fire of 1937",
  "British contribution to the Manhattan Project",
  "British Empire",
  "Brown Dog affair",
  "Burning of Parliament",
  "Byzantine Empire",
  "California Gold Rush",
  "Chalukya dynasty",
  "Clinton Engineer Works",
  "Convention of 1832",
  "Convention of 1833",
  "Confederate government of Kentucky",
  "Discovery Expedition",
  "Donner Party",
  "Exhumation and reburial of Richard III of England",
  "Farthest South",
  "Fredonian Rebellion",
  "Free State of Galveston",
  "French colonization of Texas",
  "George S. Patton slapping incidents",
  "Great Fire of London",
  "Great Stink",
  "Gunpowder Plot",
  "Halifax Explosion",
  "Han dynasty",
  "History of the Australian Capital Territory",
  "History of Burnside",
  "History of Minnesota",
  "History of Solidarity",
  "History of the Yosemite area",
  "Hoysala Empire",
  "Inner German border",
  "Iranian Embassy siege",
  "Jarrow March",
  "Jeannette Expedition",
  "June 1941 uprising in eastern Herzegovina",
  "July 2009 Ürümqi riots",
  "Kingdom of Mysore",
  "Manhattan Project",
  "Maya civilization",
  "Middle Ages",
  "Oklahoma City bombing",
  "Second Crusade",
  "Texas Revolution",
  "Political integration of India",
  "Yellowstone fires of 1988",
  "Mortara case",
  "Nyon Conference",
  "Operation Barras",
  "Southern Cross Expedition",
  "Scottish National Antarctic Expedition",
  "Plymouth Colony",
  "Peasants' Revolt",
  "Parthian Empire",
  "Operation Tungsten",
  "Spanish conquest of Guatemala",
  "United States presidential election, 1880",
  "Zanzibar Revolution",
  "Voyage of the James Caird",
  "Last voyage of the Karluk",
  "Mutiny on the Bounty",
  "7 World Trade Center",
  "Anthony Roll"
 ]
}



//"1960 South Vietnamese coup attempt", // REMOVE THIS IF HAVE ENOUGH
//"1962 South Vietnamese Independence Palace bombing",
// "New South Greenland",
// "Night of the Long Knives",
// "Norte Chico civilization",
// "Operation Passage to Freedom",
// "Political history of medieval Karnataka",
// "Political history of Mysore and Coorg (1565–1760)",
// "Red River Trails",
// "Ross Sea party 1914–16",
// "S. A. Andrée's Arctic Balloon Expedition of 1897",
// "Saint-Sylvestre coup d'état",
// "Scotland in the High Middle Ages",
// "Senghenydd colliery disaster",
// "September 1964 South Vietnamese coup attempt",
// "Slavery in ancient Greece",
// "Song dynasty",
// "Spanish conquest of Petén",
// "SS Arctic disaster",
// "Steamtown, U.S.A.",
// "Swedish emigration to the United States",
// "SY Aurora's drift",
// "",
// "Tang dynasty",
// "Terra Nova Expedition",
// ,
// "Tiananmen Square self-immolation incident",
// "Sino-Tibetan relations during the Ming dynasty",
// "",
// "",
// "Trinity (nuclear test)",
// "Vijayanagara Empire",
// "Western Chalukya Empire",
// "Western Ganga dynasty",
// "Xá Lợi Pagoda raids",
//]
